version: '3.8'

services:
  # Backend Flask Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: food-agent-backend
    ports:
      - "5001:5000"
    env_file:
      - .env  # <--- 這行設定會告訴 Docker 去讀取 .env 檔案
    volumes:
      - .:/app
      # IMPORTANT: Mount your Google Cloud credentials file into the container
      # Replace './path/to/your/credentials.json' with the actual path on your host machine
      - ./credentials.json:/app/credentials.json
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      # Set environment variables for API keys and tokens
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - LINE_CHANNEL_ACCESS_TOKEN=YOUR_LINE_CHANNEL_ACCESS_TOKEN # Replace with your LINE token
      - GOOGLE_API_KEY=GOOGLE_API_KEY # <--- 新增這一行，並換成你的金鑰

      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: flask run --host=0.0.0.0 --port=5000

  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: food-agent-frontend
    ports:
      - "5173:5173"
    environment:
      # Point the frontend to the backend service using the service name
      # The backend service is named 'backend' and listens on port 5000 internally
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

  # Redis for Celery Broker and Backend
  redis:
    image: "redis:alpine"
    container_name: food-agent-redis
    ports:
      - "6379:6379"

  # Celery Worker for Background Tasks
  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: food-agent-celery-worker
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - LINE_CHANNEL_ACCESS_TOKEN=YOUR_LINE_CHANNEL_ACCESS_TOKEN # Replace with your LINE token
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

networks:
  default:
    name: food-agent-network
