version: '3.8'

services:
  # PostgreSQL 資料庫服務
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./.env # Reads variables from .env file
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped

  # MongoDB 資料庫服務
  mongo_db:
    image: mongo:8.0 # Pinned to a specific version
    container_name: mongo_db
    env_file:
      - ./.env # Reads variables from .env file
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped

  # 後端 (Flask) 服務 (使用 uv)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    env_file:
      - ./.env
    volumes:
      # Mounts the project, but protects the container's .venv
      - .:/app
      - /app/.venv
    ports:
      - "5001:5000"
    depends_on:
      - postgres_db
      - mongo_db
    networks:
      - app-network
    restart: unless-stopped

  # 前端 (React) 服務
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

# 定義一個共用的網路，讓所有服務可以互相通訊
networks:
  app-network:
    driver: bridge